### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by didimitrie** [didimitrie/SpeckleCommon#3]
So this happens, and kills rhino.
When? Somehow a sender is on the canvas but can't send. 
```
System::Windows::Forms::Application::ThreadException event occured

SENDER: System.Threading.Thread

EXCEPTION: System.NullReferenceException
MESSAGE: Object reference not set to an instance of an object.
SOURCE: SpeckleCommon
CALL STACK
   at SpeckleCommon.SpeckleSender.sendMetadataUpdate(List`1 layers, String _name)
   at SpeckleGrasshopper.GhSenderClient.updateMetadata()
   at SpeckleGrasshopper.GhSenderClient.<AddedToDocument>b__9_2(IGH_DocumentObject sender, GH_ObjectChangedEventArgs e)
   at Grasshopper.Kernel.IGH_DocumentObject.ObjectChangedEventHandler.Invoke(IGH_DocumentObject sender, GH_ObjectChangedEventArgs e)
   at Grasshopper.Kernel.GH_DocumentObject.OnObjectChanged(GH_ObjectEventType eventType) in C:\dev\grasshopper\1.0\root\src\GH_DocumentObject.vb:line 730
   at Grasshopper.Kernel.GH_Param`1.RemoveAllSources() in C:\dev\grasshopper\1.0\root\src\GH_Param.vb:line 492
   at Grasshopper.Kernel.GH_Param`1.IsolateObject() in C:\dev\grasshopper\1.0\root\src\GH_Param.vb:line 651
   at Grasshopper.Kernel.GH_Document.InternalRemoveObject(Int32 index) in C:\dev\grasshopper\1.0\root\src\GH_Document.vb:line 1537
   at Grasshopper.Kernel.GH_Document.RemoveObjects(IEnumerable`1 objectList, Boolean update) in C:\dev\grasshopper\1.0\root\src\GH_Document.vb:line 1614
   at Grasshopper.GUI.GH_DocumentEditor.MnuDeleteClick(Object sender, EventArgs e) in C:\dev\grasshopper\1.0\root\src\GH_DocumentEditor.vb:line 1284
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at Grasshopper.GUI.GH_MenuShortCutWrapper.GenerateShortcutCommand(Keys keys, ToolStripMenuItem item) in C:\dev\grasshopper\1.0\root\src\GH_MenuShortCutWrapper.vb:line 77
   at Grasshopper.GUI.GH_MenuShortCutWrapper.GenerateShortcutCommand(Keys keys, ToolStripMenuItem item) in C:\dev\grasshopper\1.0\root\src\GH_MenuShortCutWrapper.vb:line 142
   at Grasshopper.GUI.GH_MenuShortCutWrapper.GenerateShortcutCommand(Keys keyCode, ToolStrip menu) in C:\dev\grasshopper\1.0\root\src\GH_MenuShortCutWrapper.vb:line 45
   at Grasshopper.GUI.GH_DocumentEditor.EditorKeyDown(Object sender, KeyEventArgs e) in C:\dev\grasshopper\1.0\root\src\GH_DocumentEditor.vb:line 651
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by didimitrie** [comment]
Mmm, ok I’m narrowing it down to a lack of internet connection
